# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='meow@meow.com', max_length=100),
            preserve_default=False,
        ),
    ]
