# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='author',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
